"""empty message

Revision ID: 746bf7579425
Revises: 
Create Date: 2017-09-30 13:34:20.998363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '746bf7579425'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news')
    op.drop_table('links')
    op.drop_table('tags')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tagTitle', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('owner_tags_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_tags_id'], ['news.id'], name='tags_owner_tags_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='tags_pkey'),
    sa.UniqueConstraint('tagTitle', name='tags_tagTitle_key')
    )
    op.create_table('links',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('urlTitle', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('owner_links_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_links_id'], ['news.id'], name='links_owner_links_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='links_pkey')
    )
    op.create_table('news',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('body', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('featured', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='news_pkey')
    )
    # ### end Alembic commands ###
