"""empty message

Revision ID: 8259280a9ec8
Revises: 
Create Date: 2017-10-04 19:50:08.610769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8259280a9ec8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('body', sa.String(length=1000), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('featured', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('urlTitle', sa.String(length=120), nullable=True),
    sa.Column('url', sa.String(length=120), nullable=True),
    sa.Column('owner_links_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_links_id'], ['news.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tagTitle', sa.String(length=120), nullable=True),
    sa.Column('owner_tags_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_tags_id'], ['news.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tagTitle')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags')
    op.drop_table('links')
    op.drop_table('news')
    # ### end Alembic commands ###
